#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'    
echo -e "\x1b[31m###############################################################################"
echo -e "\x1b[31m* ___     __________  ____ _______      _____ _______________.___.  ___       *"
echo -e "\x1b[31m* / _ \_/\ \______   \/_   |\      \    /  _  \\______   \__  |   | / _ \_/\  *"
echo -e "\x1b[31m* \/ \___/  |    |  _/ |   |/   |   \  /  /_\  \|       _//   |   | \/ \___/  *"
echo -e "\x1b[31m*           |    |   \ |   /    |    \/    |    \    |   \\____   |           *"
echo -e "\x1b[31m*           |______  / |___\____|__  /\____|__  /____|_  // ______|           *"
echo -e "\x1b[31m*                  \/              \/         \/       \/ \/                  *"
echo -e "\x1b[31m###############################################################################"
echo -e "\r\n\r\n\x1b[31mXMPP: b1nary@nigge.rs | Skype: bl4ck.j3sus\r\n"
echo -e "Threads: "
read threads
echo -e "IP Class: "
read ip_class
echo -e "IP Range: "
python b1naryv3.py $threads $ip_class $ip_class 2