#!/bin/bash 
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'   
exit_script()
{
  echo "* * *Trap * * *"
  ./menu
}

exit_script1()
{
  exit 1
}

Take_input1()
{
clear
while :
do
    clear
echo -e "\x1b[31m###############################################################################"
echo -e "\x1b[31m* ___     __________  ____ _______      _____ _______________.___.  ___       *"
echo -e "\x1b[31m* / _ \_/\ \______   \/_   |\      \    /  _  \\______   \__  |   | / _ \_/\  *"
echo -e "\x1b[31m* \/ \___/  |    |  _/ |   |/   |   \  /  /_\  \|       _//   |   | \/ \___/  *"
echo -e "\x1b[31m*           |    |   \ |   /    |    \/    |    \    |   \\____   |           *"
echo -e "\x1b[31m*           |______  / |___\____|__  /\____|__  /____|_  // ______|           *"
echo -e "\x1b[31m*                  \/              \/         \/       \/ \/                  *"
echo -e "\x1b[31m###############################################################################"
echo -e "\r\n\r\n\x1b[31mXMPP: b1nary@nigge.rs | Skype: bl4ck.j3sus\r\n\r\n"
echo -e "[ 1 ] Portscan"
echo -e "[ 2 ] Bruteforce List Of IPs"
echo -e "[ 3 ] BuSyBoX BaNg BuS v2"
echo -e "[ 4 ] ~B1NARY~ V3"
    read yourch
    case $yourch in
      1) ./portscan ;;
      2) ./brute ;;
      3) ./bbb ;;
	  4) ./load ;;
      *) echo "Invalid Selection, Please make another selection";
         echo "Press Enter. . ." ; read ;;
 esac
done
}
trap exit_script 2

Take_input1




